language: node_js
node_js:
  - 8.5.0
script:
  - "npm run lint"
  - "npm run test"
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
deploy:
  provider: heroku
  api_key:
    secure: ff8fc003-c659-4a56-91fc-b413d5acce0a
  app: cd-showcase
  on:
    repo: newcoder171/ride-my-way-api
